version: '3'
services:
  # Servicio MongoDB (NoSQL)
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"  # Exponer puerto para MongoDB
    volumes:
      - mongo-data:/data/db  # Persistencia de datos en MongoDB

  # Microservicio 1 - Servicio con MongoDB
  mongo_microservice:
    build: ./mongodb-microservice  # Ruta al Dockerfile del microservicio de MongoDB
    depends_on:
      - mongodb  # Espera a que MongoDB esté listo
    ports:
      - "8080:8080"  # Exponer puerto del microservicio
    volumes:
      - ./mongodb-microservice/data:/app/data  # Volumen para la app
    environment:
      MONGODB_URI: mongodb://mongodb:27017/universidad  # Conexión a MongoDB
    links:
      - mongodb  # Conexión interna a MongoDB

  # Microservicio 2 - Servicio con MySQL (SQL)
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Contraseña de MySQL
      MYSQL_DATABASE: universidad_mysql  # Base de datos a crear en MySQL
    ports:
      - "3306:3306"  # Puerto para MySQL
    volumes:
      - mysql-data:/var/lib/mysql  # Persistencia de datos en MySQL

  mysql_microservice:
    build: ./mysql-microservice  # Ruta al Dockerfile del microservicio de MySQL
    depends_on:
      - mysql  # Espera a que MySQL esté listo
    ports:
      - "8081:8081"  # Puerto para el microservicio
    environment:
      MYSQL_HOST: mysql  # Conexión interna a MySQL
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpassword
      MYSQL_DATABASE: universidad_mysql
    links:
      - mysql  # Conexión interna a MySQL

  # Microservicio 3 - Servicio con PostgreSQL (SQL)
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: universidad_postgres  # Base de datos a crear en PostgreSQL
    ports:
      - "5432:5432"  # Puerto para PostgreSQL
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persistencia de datos en PostgreSQL

  postgres_microservice:
    build: ./postgres-microservice  # Ruta al Dockerfile del microservicio de PostgreSQL
    depends_on:
      - postgres  # Espera a que PostgreSQL esté listo
    ports:
      - "8082:8082"  # Puerto para el microservicio
    environment:
      POSTGRES_HOST: postgres  # Conexión interna a PostgreSQL
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: universidad_postgres
    links:
      - postgres  # Conexión interna a PostgreSQL

volumes:
  mongo-data:
  mysql-data:
  postgres-data:
