version: '3.8'

services:

  microservicio_empresa_empleo:
    build: ./ms1  # Directorio donde est치 el Dockerfile del microservicio
    container_name: microservicio_empresa_empleo
    ports:
      - "8081:8080"  
    networks:
      - my-network
    depends_on:
      - db_mysql
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: nosejajaja123-
      MYSQL_DATABASE: microservicio2_db
      MYSQL_HOST: db_mysql
      MYSQL_PORT: 3306

  microservicio_estudiante_programa:
    build: ./ms2  # Directorio donde est치 el Dockerfile del microservicio
    container_name: microservicio_estudiante_programa
    ports:
      - "8082:8080" 
    networks:
      - my-network
    depends_on:
      - postgres-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/nuevo2
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver

  microservicio_pago_alojamiento:
    build: ./ms3  # Directorio donde est치 el Dockerfile del microservicio
    container_name: microservicio_pago_alojamiento
    ports:
      - "8083:8080"  
    networks:
      - my-network
    depends_on:
      - db_mongo
    environment:
      DATABASE_URL: mongodb://db_mongo:27017/universidad

  orquestador:
    build: ./orquestador  # Directorio donde est치 el Dockerfile del orquestador
    container_name: orquestador
    ports:
      - "5000:8080" 
    networks:
      - my-network
    depends_on:
      - microservicio_empresa_empleo
      - microservicio_estudiante_programa
      - microservicio_pago_alojamiento
    environment:
      MS1_URL: http://microservicio_empresa_empleo:8080
      MS2_URL: http://microservicio_estudiante_programa:8080
      MS3_URL: http://microservicio_pago_alojamiento:8080

  db_mysql:
    image: mysql:8.0
    container_name: db_mysql
    environment:
      MYSQL_ROOT_PASSWORD: nosejajaja123-
      MYSQL_DATABASE: microservicio2_db
    ports:
      - "3306:3306"
    networks:
      - my-network
    volumes:
      - db_mysql_data:/var/lib/mysql

  postgres-db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_DB: nuevo2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    networks:
      - my-network
    volumes:
      - pgdata:/var/lib/postgresql/data

  db_mongo:
    image: mongo:latest
    container_name: db_mongo
    ports:
      - "27017:27017" 
    networks:
      - my-network
    volumes:
      - db_mongo_data:/data/db

networks:
  my-network:
    driver: bridge

volumes:
  db_mysql_data:
  pgdata:
  db_mongo_data:
