version: '3.8'

services:
  ingesta-mysql:
    build: ./ingesta_mysql
    container_name: ingesta_mysql
    depends_on:
      - db_mysql
    environment:
      - MYSQL_HOST=db_mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=nosejajaja123-
      - MYSQL_DATABASE=microservicio2_db
    networks:
      - my-network

  ingesta-mongo:
    build: ./ingesta_mongo
    container_name: ingesta_mongo
    depends_on:
      - db_mongo
    environment:
      - MONGO_HOST=db_mongo
      - MONGO_DATABASE=universidad
    networks:
      - my-network

  db_mysql:
    image: mysql:8.0
    container_name: db_mysql
    environment:
      MYSQL_ROOT_PASSWORD=nosejajaja123-
      MYSQL_DATABASE=microservicio2_db
    ports:
      - "3306:3306"
    networks:
      - my-network

  db_mongo:
    image: mongo:latest
    container_name: db_mongo
    ports:
      - "27017:27017" 
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
