version: '3.8'

services:
  ingesta_mysql:
    image: nataliawg/ingesta_mysql:v1
    container_name: ingesta_mysql
    env_file:
      - .env
    command: ["python", "ingest_mysql.py"]
    networks:
      - ingesta_net

  ingesta_mongo:
    image: nataliawg/mongodb:v1
    container_name: ingesta_mongo
    env_file:
      - .env
    command: ["python", "ingest_mongodb.py"]
    networks:
      - ingesta_net

networks:
  ingesta_net:
    driver: bridge

volumes:
  db_data: