version: '3.8'

services:
  microservicio-estudiante:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: microservicio-estudiante
    ports:
      - "8081:8080"  # Cambia este puerto si es necesario
    networks:
      - my-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/nuevo2
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:13
    container_name: postgres-db
    environment:
      - POSTGRES_DB=nuevo2
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234

    ports:
      - "5432:5432"
    networks:
      - my-network
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  my-network:
    driver: bridge

volumes:
  pgdata:
