version: '3'
services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  alojamiento_pago_microservice:
    build: ./microservice-alojamiento-pago
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    environment:
      - MONGODB
