services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  microservice:
    build: .
    container_name: microservice-alojamiento-pago
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/universidad
    volumes:
      - ./data:/app/data
    command: ["node", "ingest_mongodb.js"]

volumes:
  mongo-data:
